version: '3.1'

services:

  db:
    image: mariadb:10.3.13
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
